### ISSUE TITLE
目錄固定在頁面右下角

### ISSUE THREAD

**Issue by HimiCos** [dhjddcn/halo-theme-butterfly#100]
### 你当前使用的halo版本

2.3.2

### 你当前使用的主题版本

2.0.5

### 你的建议

https://github.com/halo-dev/halo/issues/3584

**Comment by dhjddcn** [comment]
这里本来就是联动的

**Comment by dhjddcn** [comment]
你提issues  请带上你出问题的链接地址 这样也好排查问题

**Comment by HimiCos** [comment]
https://blog.himicos.cc/archives/html-css-sprites

**Comment by HimiCos** [comment]
如遇相同問題，請關閉瀏覽器 AdBlock 插件
