### ISSUE TITLE
首页可否添加登录和后台跳转的按钮

### ISSUE THREAD

**Issue by qqqzh** [dhjddcn/halo-theme-butterfly#101]
### 你当前使用的halo版本

2.3.2

### 你当前使用的主题版本

2.0.4

### 你的建议是否涉及到一些现有的问题？

-

### 描述你想实现的效果

能否在首页页眉处加上登录和后台跳转的按钮呢？初用了一下发现好像只能通过/console来手动登录然后进入后台界面，不是很方便呢。。

**Comment by dhjddcn** [comment]
这属于无效功能 你可以去菜单加一个菜单跳转至管理页面
