### ISSUE TITLE
自动生成摘要不起作用，前台列表页不显示摘要

### ISSUE THREAD

**Issue by wynn0123** [dhjddcn/halo-theme-butterfly#103]
### 是什么版本出现了此问题？

2.0.3

### Halo 版本

2.3.1

### 主题 版本

2.0.3

### 平台

桌面端

### 在线站点地址

https://ojson.com

### 描述缺陷

![image](https://user-images.githubusercontent.com/129109083/228050096-4a04b151-d0ad-416b-b163-2a0f290570d6.png)
自动生成摘要不起作用，前台列表页不显示摘要

### 附加信息

![image](https://user-images.githubusercontent.com/129109083/228051006-ea9c104e-d825-4d68-9f41-4761eb7c496f.png)

另外，列表页的**点赞**是哪来的，一直都是0

**Comment by dhjddcn** [comment]
摘要功能，和点赞功能 请关注halo的动态

**Comment by dhjddcn** [comment]
更新一下版本吧  最新版2.0.5了

**Comment by wynn0123** [comment]
> 更新一下版本吧 最新版2.0.5了

**已更新，但bug还是存在。**

以下我提供解决方案：
经过我查询官方开发文档如下：
![image](https://user-images.githubusercontent.com/129109083/228256849-9bb43005-1415-42d2-92b0-b5bd1e0e5182.png)

修改主题modules/public.html文章列表那一段，将 `${post.spec.excerpt.raw}` 改为 `${post.status.excerpt}` 即可显示出最终摘要

![image](https://user-images.githubusercontent.com/129109083/228257508-ac24c9fe-e5ad-46a6-bada-2ba2efa85018.png)
