### ISSUE TITLE
500 Internal Server Error Exception evaluating SpringEL expression: "bt[1]" (template: "modules/public" - line 34, col 68)

### ISSUE THREAD

**Issue by CC342** [dhjddcn/halo-theme-butterfly#109]
### 是什么版本出现了此问题？

2.05

### Halo 版本

2.3.2

### 主题 版本

 theme-butterfly

### 平台

桌面端

### 在线站点地址

sss

### 描述缺陷

500
Internal Server Error
Exception evaluating SpringEL expression: "bt[1]" (template: "modules/public" - line 34, col 68)

我在编辑文章，点击预览就变成这样了..555

**Comment by dhjddcn** [comment]
侧边栏的按钮设置 你看下你是不是设置错误了
