### ISSUE TITLE
背景图设置问题

### ISSUE THREAD

**Issue by Apathy94** [dhjddcn/halo-theme-butterfly#11]
你好，该怎么设置才能使背景图如何充满整个页面
而不是这样分层
<img width="2017" alt="Screen Shot 2022-02-09 at 17 00 15" src="https://user-images.githubusercontent.com/25723005/153161105-4a74bd4b-05d7-4e51-b7e5-8806fcf9aa48.png">
谢谢

**Comment by CieanYau0** [comment]
后续会在设置内添加选项，可以关注一下developer-cieanyau分支

**Comment by dhjddcn** [comment]
![image](https://user-images.githubusercontent.com/52057336/154257368-8576b7e9-5659-4ada-94ff-f4145f6f7807.png)

**Comment by Apathy94** [comment]
> ![image](https://user-images.githubusercontent.com/52057336/154257368-8576b7e9-5659-4ada-94ff-f4145f6f7807.png)

好的，谢谢

**Comment by Apathy94** [comment]
> 后续会在设置内添加选项，可以关注一下developer-cieanyau分支

好的
