### ISSUE TITLE
菜单打开方式错乱

### ISSUE THREAD

**Issue by leealu** [dhjddcn/halo-theme-butterfly#111]
### 是什么版本出现了此问题？

2.4.0

### Halo 版本

2.4.0

### 主题 版本

2.0

### 平台

桌面端

### 在线站点地址

blog.801100.tk

### 描述缺陷

1：桌面端的菜单链接一级打开都是新窗口不管怎么设置没用，移动端也一样；
2：菜单的二级菜单不管怎么设置都是当前窗口打开，移动端也一样。

**Comment by dhjddcn** [comment]
已经有相关 issues
