### ISSUE TITLE
全局背景图无效果

### ISSUE THREAD

**Issue by bigmouse0001** [dhjddcn/halo-theme-butterfly#117]
### 是什么版本出现了此问题？

v2.0.5

### Halo 版本

 2.5.2

### 主题 版本

v2.0.5

### 平台

桌面端

### 操作系统

ubuntu20.04.6

### 浏览器

chrome113.0.5672.64（正式版本） （64 位）

### 在线站点地址

logic.any168.net

### 描述缺陷

禁用所有第一屏背景图，设置全局背景图为：[文件](https://github.com/dhjddcn/halo-theme-butterfly/assets/119995454/23d98a2b-0dc7-44c5-9ff0-35c46f5b17d1)
![R_2449x1632](https://github.com/dhjddcn/halo-theme-butterfly/assets/119995454/23d98a2b-0dc7-44c5-9ff0-35c46f5b17d1)

不起作用~

### 期望结果

人生第一次做blog，麻烦哥哥姐姐们帮我看下，谢谢~~

**Comment by dhjddcn** [comment]
请使用 全连接的
