### ISSUE TITLE
主体的顶部背景图高度设置不生效

### ISSUE THREAD

**Issue by zyy24796143** [dhjddcn/halo-theme-butterfly#12]
主体的顶部背景图高度设置不生效，调了30vh，在首页里面显示的还是100vh

**Comment by CieanYau0** [comment]
请提供截图

**Comment by zyy24796143** [comment]
网址是这个 https://www.seafog.cn/ ，目前后台设置的是50vh，前端看到的还是100vh

![image](https://user-images.githubusercontent.com/25009398/154391459-08e74a92-015d-446b-94c7-061e999f75cb.png)

**Comment by dhjddcn** [comment]
你好 这个设置是开发初期预设的  但是后面因为一些问题没有开发  🙊

**Comment by zyy24796143** [comment]
原来这样子

**Comment by dhjddcn** [comment]
非常抱歉  给你带来了不便🙊

**Comment by dhjddcn** [comment]
会考虑

**Comment by CieanYau0** [comment]
这个我可以试试，后续更新可以关注一下developer-cieanyau分支

**Comment by dhjddcn** [comment]
1

**Comment by dhjddcn** [comment]
2.0 已经移除
