### ISSUE TITLE
文章编辑器里的样式描述出现在了已发布的文章中

### ISSUE THREAD

**Issue by LeoLinbogate** [dhjddcn/halo-theme-butterfly#124]
### 是什么版本出现了此问题？

2.7

### Halo 版本

2.7

### 主题 版本

2.0.5

### 平台

桌面端

### 在线站点地址

内网

### 描述缺陷

如图所示，前面的H1段落格式名称，出现在了发布出去的文章中
<img width="456" alt="image" src="https://github.com/dhjddcn/halo-theme-butterfly/assets/39193439/2296d563-53c3-4dd2-b074-21e8d1491f6e">

**Comment by dhjddcn** [comment]
不是bug  有设置
