### ISSUE TITLE
感觉在计算阅读时长的部分存在计算问题

### ISSUE THREAD

**Issue by llody55** [dhjddcn/halo-theme-butterfly#125]
### 是什么版本出现了此问题？

    2.0.5

### Halo 版本

2.5

### 主题 版本

2.0.5

### 平台

桌面端

### 操作系统

centos7

### 在线站点地址

https://www.llody.top/archives/yun-cun-chu-ji-shu-de-shen-qi--rclone

### 描述缺陷

阅读时长的计算部分感觉有问题，2万个字左右，需要花费1个半小时进行阅读吗？

### 如何复现

可以查看我提供网址连接

**Comment by dhjddcn** [comment]
已经有相关的 issues 了

**Comment by llody55** [comment]
@dhjddcn 好的
