### ISSUE TITLE
宽度

### ISSUE THREAD

**Issue by Ezgx** [dhjddcn/halo-theme-butterfly#126]
### 是什么版本出现了此问题？

最新版

### Halo 版本

11.45.14

### 主题 版本

19.19.810

### 平台

桌面端

### 操作系统

homo-OS

### 浏览器

Tian-Suo-Hao-Er_browser

### 在线站点地址

none

### 描述缺陷

宽度抄错啦

### 如何复现

none

### 期望结果

主部分的宽度应该是1200px
![image](https://github.com/dhjddcn/halo-theme-butterfly/assets/110729988/74e2b7c2-9d52-434d-8315-cd04ac39cbf0)
你这里是1500px（）

### 附加信息

none

**Comment by dhjddcn** [comment]
这个移植并非全部从之前主题上抄过来，也有我自己加入的一部分内容
