### ISSUE TITLE
使用默认用户名Administrator不能显示个人资料

### ISSUE THREAD

**Issue by GMYXDS** [dhjddcn/halo-theme-butterfly#129]
### 是什么版本出现了此问题？

v2.0.5

### Halo 版本

2.8.0

### 主题 版本

v2.0.5

### 平台

桌面端

### 操作系统

win 10

### 浏览器

edge

### 在线站点地址

https://halo.kaopuju.com/

### 描述缺陷

如上
已经设置 Halo Console - 用户 - 用户详情 - 用户名
右侧个人资料卡任然不能更新
新建一个普通用户，则可以

### 如何复现

docker 安装最新版halo
安装halo-theme-butterfly
配置用户名为超级管理员的用户名
出现删除的用户

### 期望结果

能够显示超级管理员的信息

**Comment by dhjddcn** [comment]
配置 metadata.name
