### ISSUE TITLE
文章目录跳转问题

### ISSUE THREAD

**Issue by JYBeYonDing** [dhjddcn/halo-theme-butterfly#132]
### 是什么版本出现了此问题？

2.0.5

### Halo 版本

2.8.0

### 主题 版本

2.0.5

### 平台

桌面端

### 操作系统

macos

### 浏览器

chome

### 在线站点地址

http://blog.jamesyoung94.top:8081/console/posts/editor?name=c4d41f46-ff21-4c8b-9fe9-e010c953c720

### 描述缺陷

文章目录
用了bytemd插件后，在预览视图是生效的，但是发布后点击目录始终跳转到开头，麻烦看下

### 如何复现

正常操作点击文章目录复现

### 期望结果

正常跳转到指定目录

**Comment by YBYCS** [comment]
同有此问题

**Comment by dhjddcn** [comment]
建议使用官方编辑器哈，md插件因为各有差距，不好适配
