### ISSUE TITLE
本站访客和总访问量统计不准确

### ISSUE THREAD

**Issue by MarkZeng222** [dhjddcn/halo-theme-butterfly#136]
### 是什么版本出现了此问题？

2.0.5

### Halo 版本

2.11

### 主题 版本

2.0.5

### 平台

桌面端

### 操作系统

Windows 11

### 浏览器

Chrome

### 在线站点地址

无

### 描述缺陷

<img width="277" alt="image" src="https://github.com/dhjddcn/halo-theme-butterfly/assets/25235188/e2ef9cba-3db9-4b53-a2b1-0ad3906c21f5">

网站没有上线，现在只有我一个人进行测试，不可能有这么多访客。

### 期望结果

请指导如何修复这个问题，谢谢

**Comment by fanganpai** [comment]
同问

**Comment by dhjddcn** [comment]
如果是本地127.0.0.1 或者 127.0.0.1  访客就是这么多哈

**Comment by dhjddcn** [comment]
因为之前用的卜算子访客计算

**Comment by dhjddcn** [comment]
后续后使用halo 自带的进行计算
