### ISSUE TITLE
网站咨询-本站访客不可用

### ISSUE THREAD

**Issue by boolean-dev** [dhjddcn/halo-theme-butterfly#137]
### 是什么版本出现了此问题？

v2.0.5

### Halo 版本

2.11.2

### 主题 版本

v2.0.5

### 平台

桌面端

### 操作系统

Win11

### 浏览器

Chrome & FireFox

### 在线站点地址

https://blog.booleandev.xyz/

### 描述缺陷

网站访客不可用：
![图片](https://github.com/dhjddcn/halo-theme-butterfly/assets/20177406/ff9e5469-786b-4312-882b-e41e19c87964)

大概原因是请求这个地址 502：
https://busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback_722694265525

![图片](https://github.com/dhjddcn/halo-theme-butterfly/assets/20177406/fac14349-96c0-4e85-9c72-a8909127bf88)

**Comment by dhjddcn** [comment]
之前站点统计是卜算子的 ，后续会采用halo的 再带的访客数据
