### ISSUE TITLE
手机端的侧边栏无法切换暗色模式

### ISSUE THREAD

**Issue by LittleY98** [dhjddcn/halo-theme-butterfly#138]
### 是什么版本出现了此问题？

2.0.5

### Halo 版本

2.0.0

### 主题 版本

halo-theme-butterfly  2.0.5

### 平台

移动端

### 操作系统

IOS

### 浏览器

Safari

### 在线站点地址

https://dhjdd.cn/

### 描述缺陷

![截图 2024-01-25 13-11-45](https://github.com/dhjddcn/halo-theme-butterfly/assets/47181393/8f72676b-6d52-41bc-8b89-767c74b24989)

### 如何复现

手机打开 [https://dhjdd.cn/](https://dhjdd.cn/)，切换到暗色模式，然后点击侧边栏

**Comment by dhjddcn** [comment]
这个没有适配暗色模式
