### ISSUE TITLE
导航菜单取值错误

### ISSUE THREAD

**Issue by Flik6** [dhjddcn/halo-theme-butterfly#139]
### 是什么版本出现了此问题？

2.0.5

### Halo 版本

2.11

### 主题 版本

2.0.5

### 平台

桌面端

### 在线站点地址

https://bbs.92coco.cn:8443/

### 描述缺陷

# 问题
关联问题https://github.com/dhjddcn/halo-theme-butterfly/issues/110
导航栏菜单a标签取值错误，值为SELF 应该为_self才可以在当前窗口打开
![image](https://github.com/dhjddcn/halo-theme-butterfly/assets/19778582/5d593ef9-5d38-4f90-adcf-e5dbdeef06d0)
查看源码发现
![image](https://github.com/dhjddcn/halo-theme-butterfly/assets/19778582/d19e9653-66f6-4150-b00e-d23a49fe4b9a)
这块取值错误
# 修复方法 
将th:target修改为menuItem.spec.target?.value
即
![image](https://github.com/dhjddcn/halo-theme-butterfly/assets/19778582/3be49a9a-690b-46dd-906a-988e72687954)

**Comment by Flik6** [comment]
![image](https://github.com/dhjddcn/halo-theme-butterfly/assets/19778582/bc0aa64c-8f0b-47d0-9099-9aa34d521ed3)

修改后正常的样子

**Comment by dhjddcn** [comment]
目前新版本正在开发中，次问题已经修复暂时还未发布
