### ISSUE TITLE
字体怎么改成你博客的那个字体啊？

### ISSUE THREAD

**Issue by li-xunhuan** [dhjddcn/halo-theme-butterfly#14]
后台设置里面的字体是这样的

![image](https://user-images.githubusercontent.com/10476982/154790080-b1db6af9-bf7d-4a6e-b9b0-6adde47c177d.png)

**Comment by CieanYau0** [comment]
设置内有字体调整

**Comment by li-xunhuan** [comment]
改了，没得效果才来问的~


![image](https://user-images.githubusercontent.com/10476982/154792383-25865e7a-2ae6-4d33-9d67-51fd83479b46.png)

**Comment by leijue222** [comment]
可否增加宋体、楷体这类字体？

**Comment by dhjddcn** [comment]
可以自己添加字体文件
