### ISSUE TITLE
本文链接和摘要未正确显示

### ISSUE THREAD

**Issue by manjieqi** [dhjddcn/halo-theme-butterfly#140]
### 是什么版本出现了此问题？

docker版本？

### Halo 版本

2.14.1

### 主题 版本

2.0.5

### 平台

桌面端

### 在线站点地址

https://halo.manjieqi.cn/

### 描述缺陷

<img width="530" alt="Snipaste_2024-04-26_15-51-07" src="https://github.com/dhjddcn/halo-theme-butterfly/assets/40858189/6f56dd3f-ee72-4285-9c48-a86ee303f5d1" style="border:2px dashed;">

如图，本文链接未显示完整，docker环境变量已经设置了外部访问链接，并且光标放上去，浏览器左下角的链接是完整的

<img width="229" alt="Snipaste_2024-04-26_16-34-18" src="https://github.com/dhjddcn/halo-theme-butterfly/assets/40858189/14e01aaa-b0c2-46ff-a398-ef12d2b8b3cd">

没有显示摘要，按照[#103](https://github.com/dhjddcn/halo-theme-butterfly/issues/103)操作，没有反应

**Comment by dhjddcn** [comment]
收到
