### ISSUE TITLE
侧边栏中分类支持显示个数、显示全层级、根级、树结构显示、可选择平铺/列表

### ISSUE THREAD

**Issue by Jollyup** [dhjddcn/halo-theme-butterfly#143]
### 你当前使用的halo版本

2.16.3

### 你当前使用的主题版本

2.0.5

### 你的建议是否涉及到一些现有的问题？

![Uploading image.png…]()
分类显示不全，我创建的分类比较多

### 描述你想实现的效果

- 分类显示支持 列表/平铺/树结构
- 支持显示个数
- 分类支持显示 根分类或者全层级分类显示

**Comment by dhjddcn** [comment]
建议去分类页面查看所有标签，侧边栏只是一个简略显示

**Comment by Jollyup** [comment]
好的
