### ISSUE TITLE
首页向下箭头无法点击

### ISSUE THREAD

**Issue by songxychn** [dhjddcn/halo-theme-butterfly#146]
### 是什么版本出现了此问题？

2.0.5

### Halo 版本

2.18

### 主题 版本

2.0.5

### 平台

桌面端

### 浏览器

chrome

### 在线站点地址

https://baizhukui.com/

### 描述缺陷

首先非常感谢作者！这是我见过最漂亮的博客主题！从hexo到halo一直在用。
![image](https://github.com/user-attachments/assets/31f56980-0f08-4e3c-99ec-e73b49c6c281)
首页向下箭头无法点击，再加上整个屏幕都被头图占满，部分用户不知道如何查看文章，误以为博客卡住

### 期望结果

首页向下箭头点击后可以向下滚动至首页图下方

**Comment by dhjddcn** [comment]
次问题在下一个版本中修复
