### ISSUE TITLE
文章详情的分类展示优化建议

### ISSUE THREAD

**Issue by guqing** [dhjddcn/halo-theme-butterfly#15]
## 描述
当文章所属多个分类时，详情页分类堆积在了一起，建议使用分隔符或其他方式优化显示
<img width="548" alt="image" src="https://user-images.githubusercontent.com/38999863/155644363-4b5a3acf-1db4-40bb-95ec-009b4b06ff61.png">

**Comment by dhjddcn** [comment]
2.0 已经优化
