### ISSUE TITLE
LaTex支持

### ISSUE THREAD

**Issue by zhou431615** [dhjddcn/halo-theme-butterfly#18]
无论是行级的还是块级的LaTex的数学公式，还是非常简单的数学符号都不支持插入。请尽快支持一下吧。

**Comment by zhou431615** [comment]
好消息！在今日推出的新版本Halo 1.5.0增加对于数学公式做了优化。在Halo 1.5.0中，数学公式仅需要在前台引入kate.css，引入如下：`<link rel="stylesheet" href="https://unpkg.com/katex@0.12.0/dist/katex.min.css" />`

**Comment by dhjddcn** [comment]
😀😀
