### ISSUE TITLE
支持文章的搜索吗

### ISSUE THREAD

**Issue by qiyuan-xinlan** [dhjddcn/halo-theme-butterfly#19]
发现如果文章多了，找起来就费劲了，首页闪烁的光标貌似也不是搜索~

**Comment by dhjddcn** [comment]
下个版本支持

**Comment by momosnail** [comment]
前辈，带搜索功能的下个版本啥时候发布，能不能给个大致时间，让我抱有希望 ，谢谢。我自己的技术文章几百篇太多了，要找到某个自己写过的博客，没有搜索功能 就是大海捞针，跪求前辈更新！！！

**Comment by dhjddcn** [comment]
这个模板可能会更换 因为halo马上会发布 2.0 模板相应的也会变更 所以准备新模板重写

**Comment by dhjddcn** [comment]
你加我QQ吧

**Comment by dhjddcn** [comment]
2.0 使用官方的搜索插件 使用需要下载halo官方搜索插件安装

**Comment by momosnail** [comment]
> 2.0 使用官方的搜索插件 使用需要下载halo官方搜索插件安装

好的 谢谢
