### ISSUE TITLE
markdown中有序列表不会显示

### ISSUE THREAD

**Issue by Ezreal147** [dhjddcn/halo-theme-butterfly#2]
![`CRS56CZ$(3AXUJHYC}2KMJ](https://user-images.githubusercontent.com/29727034/151692497-6ecfe2a2-51f4-4f1e-9006-a53945d2c4e4.png)
![L9JL1TK4~ A1EA_{S{DN2VD](https://user-images.githubusercontent.com/29727034/151692536-33317106-ee1c-4810-b833-b56c2a4a263a.png)

**Comment by dhjddcn** [comment]
好的 收到

**Comment by Ezreal147** [comment]
> 好的 收到

还有区块也无法正常显示

**Comment by dhjddcn** [comment]
截图看一下呐  我这边都是正常的呐

**Comment by Ezreal147** [comment]
编辑界面
![1643600898(1)](https://user-images.githubusercontent.com/29727034/151736214-1fffd306-76fc-4dc1-927f-995df16d0b7f.png)
实际渲染结果
![1643600958(1)](https://user-images.githubusercontent.com/29727034/151736247-1c483924-cecc-4398-92dc-183f72e1f5da.png)
这样一对比区块文本和普通文本好像确实不一样，但是感觉难以区分啊，不像编辑界面的预览效果里区块左边有一条的

**Comment by dhjddcn** [comment]
好的 收到

**Comment by Ezreal147** [comment]
还有想请教您一下这样的效果是怎么实现的？html吗？
![image](https://user-images.githubusercontent.com/29727034/151736638-0b3e592a-9aa0-4402-927e-e6fdf7a719fb.png)
![image](https://user-images.githubusercontent.com/29727034/151736659-1566150b-bf30-4689-ad5d-92fad740df20.png)

**Comment by dhjddcn** [comment]
这个 要自己编写 html  css   这些扩展标签现在只引入了css   后续我会扩展标签   <my-msg/  m="消息 " > 这一种的形式

**Comment by Ezreal147** [comment]
好的谢谢

**Comment by dhjddcn** [comment]
2.0 已经修复
