### ISSUE TITLE
文章详情页 右侧【目录】的分类和跳转问题

### ISSUE THREAD

**Issue by lhchong** [dhjddcn/halo-theme-butterfly#21]
1、文章详情页 右侧 【目录】分类没有按照md的层级进行划分，是否能优化下，体验应该会更好。
<img width="1002" alt="3" src="https://user-images.githubusercontent.com/34005860/160221280-ecc1f329-1182-4c91-85de-297c86314d82.png">
<img width="1007" alt="4" src="https://user-images.githubusercontent.com/34005860/160221285-6df2b0fd-34ac-46ca-a343-777cca2e846c.png">

2、文章详情页 右侧【目录】分类 点击后没有跳转到指定位置，而是页面向上移动了一点点。

**Comment by dhjddcn** [comment]
新版本 正在开发中 详情进群讨论

**Comment by lhchong** [comment]
好的，了解

**Comment by 1598142191** [comment]
群是什么呀 @dhjddcn

**Comment by lhchong** [comment]
> 

916571927
