### ISSUE TITLE
一点小反馈：留言板功能缺失、教程参考有模糊

### ISSUE THREAD

**Issue by rT-Troy** [dhjddcn/halo-theme-butterfly#25]
你好！

1.不知道是主题开发未涉及到留言板功能还是我域名错误，/comments 页面是空白的。

2.README.md最后一点关于如何自定义导航条菜单图标？有点错误

`<i class="by-font by-icon-xxx"></i>` 应为 `<i class="by-font by_icon_xxx"></i>` 实际xxx处需对照网站填写中文的拼音即可。

期待回复
祝好

**Comment by dhjddcn** [comment]
好的谢谢 感谢你的反馈  主题目前还没有评论以及留言
