### ISSUE TITLE
公网安备号填写后页面没有展示

### ISSUE THREAD

**Issue by juning98** [dhjddcn/halo-theme-butterfly#26]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/20538542/162402144-e1c2a82c-ad31-4f78-b8ab-43a57b25fe36.png">
我已经填写了公网安备号，但是网页上并没有显示它
<img width="848" alt="image" src="https://user-images.githubusercontent.com/20538542/162402295-aa864a6c-fabf-46d7-9bcd-52f1224db756.png">

**Comment by CieanYau0** [comment]
尝试使用Developer-cieanyau分支

**Comment by juning98** [comment]
已使用  希望能够早点用上master分支
