### ISSUE TITLE
提个问题和建议

### ISSUE THREAD

**Issue by jeremyzhong7** [dhjddcn/halo-theme-butterfly#29]
你好！请问一下首页的“关注我”是还没开发完毕嘛 点击之后是开了一个新的首页标签
![image](https://user-images.githubusercontent.com/59838072/163340880-03d407ab-b543-4148-89d2-09a6fbfebbad.png)
还有我真的很喜欢这个theme！美中不足还是缺少评论，作者大大加油。

**Comment by dhjddcn** [comment]
😂目前的版本感觉 bug 太多了 所有我现在在重构 由于目前工作比较忙所以可能开发延后了   谢谢你的支持🌹

**Comment by jeremy526** [comment]
好的 感谢！
