### ISSUE TITLE
公安网备信息未显示

### ISSUE THREAD

**Issue by CieanYau0** [dhjddcn/halo-theme-butterfly#3]
设置ICP备案信息后，可以显示ICP备案，但是设置公安网备信息后，并没有显示公安网备的信息
不知道是不是我的设置问题

**Comment by CieanYau0** [comment]
![image](https://user-images.githubusercontent.com/78378239/152489258-320f56f7-40e1-4cb7-8a37-4aeaa31024ad.png)
![image](https://user-images.githubusercontent.com/78378239/152489351-c7bdf720-3563-46c9-8c5c-2d235f319264.png)

**Comment by dhjddcn** [comment]
好的 收到

**Comment by akin-azure** [comment]
我也遇到同样的问题，是否有人解决了呢
