### ISSUE TITLE
body背景图片更换问题，以及背景彩带动画无法关闭。

### ISSUE THREAD

**Issue by linken404** [dhjddcn/halo-theme-butterfly#32]
是两个问题，我在设置里面试了一遍没有找到解决方法：
1、在【主题设置 -- body背景图可选】项，点击上传按钮更换背景图片后，上传的图片（引用方式为”/upload/xxx“）无法作为背景生效，仍然是默认背景。
2、在【主题设置 -- body背景图可选】项，填写RGB值或http图片直链，背景可生效，但背景彩带动画仍然存在，未找到关闭选项。

**Comment by Jason-2k** [comment]
请问该文件在哪里？找遍了主题包也没有找到


> silk.js
> 
> ```js
>         init: function() {
>             // try { this._canvas = document.createElement("canvas"), this._canvas.setAttribute("style", "position:fixed;z-index:0;left:0;top:0;right:0;bottom:0;pointer-events:none;"), this._canvas.id = "bgCanvas", this._onResize(), this._context = this._canvas.getContext("2d"), this._context.clearRect(0, 0, this._width, this._height), this._context.globalAlpha = this._options.colorAlpha, window.addEventListener("resize", this._onResize), window.addEventListener("scroll", this._onScroll), document.body.appendChild(this._canvas); } catch (t) { return void console.warn("Canvas Context Error: " + t.toString()); }
>             // this._onDraw();
>         },
> ```
> 
> 注释掉就没了
