### ISSUE TITLE
Bug与改进建议

### ISSUE THREAD

**Issue by LemonSoldOut** [dhjddcn/halo-theme-butterfly#33]
1. 博客后台 - 主题设置 - 侧边栏 - 信息按钮模板应该不是 跳转文字|跳转url 而是 跳转文字||跳转url。如果只有 1 个 '|' 就会出错，在博客页面按钮里面直接显示代码，像背景彩带等一些渲染就直接无了
2. 博客后台 - 主题设置 - 社交 - 邮箱需要用户以 "mailto:xxxxxxxx@yyy.com" 的形式才能在页面中正确打开邮件，希望能改进一下
3. 博客页面，无论是主页面还是文章正文页面点击左上角主页跳转按钮都无法回到主页，像是在当前 url 下直接附加了主页的地址，比如主页下就是 xxx.com/xxx.com，正文下就是 xxx.com/archives/xxx.com
4. 好像没有图库功能，评论功能也没看到希望能加一下
5. 新用户刚开始用，如果有其他bug会持续反馈~ (这主题是真滴好康 qwq)

**Comment by dhjddcn** [comment]
好的 收到

**Comment by NuriAlfred** [comment]
邮箱点击直接404 必须mailto:开头才能链接 同感+1

**Comment by CieanYau0** [comment]
收到，将在下一版本更新

**Comment by dhjddcn** [comment]
2.0 已修复
