### ISSUE TITLE
C#代码未高亮

### ISSUE THREAD

**Issue by Redns** [dhjddcn/halo-theme-butterfly#39]
添加 C# 代码块时，渲染出来显示 Plain text 且无高亮，修改代码块标识为 Java 就可以高亮

【代码块标识为 C#】
![image](https://user-images.githubusercontent.com/69022576/169189629-06ce2c6d-5ea1-472b-a427-242adc98639b.png)

【代码块标识为 Java】
![image](https://user-images.githubusercontent.com/69022576/169189719-b2515e4b-48e2-4cb8-85ca-96976e0537a7.png)

**Comment by lzwcn** [comment]
代码块标识改成 `csharp`，应该就可以了

**Comment by Redns** [comment]
果然可以，感谢！
