### ISSUE TITLE
Markdown引用语法无法渲染

### ISSUE THREAD

**Issue by Redns** [dhjddcn/halo-theme-butterfly#40]
本地环境可以正常渲染
![image](https://user-images.githubusercontent.com/69022576/169281121-dab629b5-5020-470d-8240-2b46c406c3b3.png)
网页端无法渲染
![image](https://user-images.githubusercontent.com/69022576/169281191-b4caf699-2c1a-4478-9bcd-e8d87a70c471.png)

**Comment by Willxup** [comment]
我也遇到了，使用markdown引用语法显示的是没有任何特效的文本，如果在引用中指定{.note}会出现引用，但显示不出引用图标，只有个小框。

**Comment by Redns** [comment]
应该不是，Anatole 主题下可以渲染

![image](https://user-images.githubusercontent.com/69022576/174783119-0e897bd2-bd34-41b1-b015-f6384a94d92e.png)
