### ISSUE TITLE
目录无法跳转问题！！！

### ISSUE THREAD

**Issue by UNIONDONG** [dhjddcn/halo-theme-butterfly#43]
非常喜欢大大的风格，但是很头疼的问题就是目录无法跳转，我看有些同学也遇到了，说是中文无法跳转，而我的 中英文都不行呢！！！求助！！！

**Comment by CieanYau0** [comment]
收到，将在下一版本修复

**Comment by JYBeYonDing** [comment]
用了bytemd插件后，在预览视图是生效的，但是发布后点击始终跳转到开头，麻烦看下
