### ISSUE TITLE
如何能让每篇文章不以封面图为顶部背景图？

### ISSUE THREAD

**Issue by YotsugiO** [dhjddcn/halo-theme-butterfly#46]
当开启全局顶部背景图和文章顶部背景图时，每篇文章的顶部背景图会自动更换为这篇文章的封面图。而我想让每篇文章的顶部背景图与其他页面，如文章分类、首页等的顶部背景图保持一致，那么该如何设置或修改文件呢？恳请赐教，感谢！

**Comment by dhjddcn** [comment]
主题目前不支持这种，如果想要可以自行设计修改代码

**Comment by YotsugiO** [comment]
非常喜欢这款主题，谢谢回复！

**Comment by YotsugiO** [comment]
非常喜欢这款主题，谢谢回复！
