### ISSUE TITLE
请问有教程么？大佬

### ISSUE THREAD

**Issue by Sinsoledads** [dhjddcn/halo-theme-butterfly#50]

**Comment by dhjddcn** [comment]
？什么

**Comment by Sinsoledads** [comment]
有没有类似 一些博客设置的教程 想问

**Comment by dhjddcn** [comment]
后台不是有吗  都有些 设置的意思

**Comment by Sinsoledads** [comment]
嗯，明白了，不过我设置完博客  头像都不存在了

**Comment by dhjddcn** [comment]
站点发一下

**Comment by Sinsoledads** [comment]
https://halo-5ghboncgcdd4f516-1258806175.ap-shanghai.app.tcloudbase.com/

**Comment by dhjddcn** [comment]
https://cn.gravatar.com/avatar/0a6651706ad1d0bc66c83bbc71bb1d94?s=256&d=mm

**Comment by dhjddcn** [comment]
你这个头像加载不出来。

**Comment by Sinsoledads** [comment]
这个是博客的默认头像吧  设置里面好像没有地方 配置

**Comment by dhjddcn** [comment]
那是halo的设置 不是主题的设置

**Comment by Sinsoledads** [comment]
好滴 我明白了
