### ISSUE TITLE
主题社交中qq地址调用问题

### ISSUE THREAD

**Issue by PulSe-kun** [dhjddcn/halo-theme-butterfly#54]
第一次使用这个主题，很好看。
但是我在替换自己qq号后，遇到：
1.在社交中 调用qq这个有些问题，我在测试中会提示我需要更新qq最新版本，实际我已经是最新版本；
2.手机端点击 会跳转失败，看起来这个地址只针对网页；
![image](https://user-images.githubusercontent.com/66857592/217735879-0f7946e0-fa66-46b5-befc-f6074d51b074.png)

后续我查到是权限问题， 使用qq这个接口更好些，手机端和网页端正常使用：
https://api.sumt.cn/api/qq.talk.php?qq=自己的QQ号&format=card

**Comment by dhjddcn** [comment]
好的 感谢你提出的问题 👍👍
