### ISSUE TITLE
文章标题前带H1，H2

### ISSUE THREAD

**Issue by metfairy** [dhjddcn/halo-theme-butterfly#55]
1. 文章标题前带H1，H2，
2. 分类的结果貌似是逆序的，没有显示所有的分类。

**Comment by metfairy** [comment]
使用的是默认编辑器

**Comment by dhjddcn** [comment]
请提供你的截图   以及详细解释

**Comment by metfairy** [comment]
你看这个 https://www.liuyg.cn/archives/mysql20230109

**Comment by dhjddcn** [comment]
文章标题前带H1，H2，这个是我预制的  h1-h6都带有相应的一个图标

**Comment by metfairy** [comment]
OK

**Comment by Chen735** [comment]
> 

那么我如何隐藏标题前的H1或者H2 的显示呢
