### ISSUE TITLE
文章详情页最新文章列表 日期错误

### ISSUE THREAD

**Issue by z0sen** [dhjddcn/halo-theme-butterfly#56]
开始以为是我的博客问题，后查看了你的博客发现存在同样问题，详情看图：
<img width="334" alt="image" src="https://user-images.githubusercontent.com/49097104/218366093-059a2ba7-8c1e-44e7-90e5-96d7d38e9dd9.png">

**Comment by dhjddcn** [comment]
😂 好的 我抽空看一下
