### ISSUE TITLE
已将主题与hola2.2适配的tocbot更新最新但tocbot目录点击无跳转

### ISSUE THREAD

**Issue by xyh2132** [dhjddcn/halo-theme-butterfly#60]
点击tocbot生成的目录,直接跳转到最顶部,并未跳转到相应块
同时设置文章主页首图高度无效

**Comment by dhjddcn** [comment]
请检查你的 文章md 解析html 是否有id

**Comment by dhjddcn** [comment]
请提你的站点 或者截图

**Comment by PulSe-kun** [comment]
> 点击tocbot生成的目录,直接跳转到最顶部,并未跳转到相应块 同时设置文章主页首图高度无效

是官方md插件问题 没有标识id ，看到也有人在那提Issues了
