### ISSUE TITLE
图片回显有时候看不到

### ISSUE THREAD

**Issue by wsy000-com** [dhjddcn/halo-theme-butterfly#64]
### 是什么版本出现了此问题？

2.2.0

### Halo 版本

2.2.0

### 平台

桌面端

### 描述缺陷

有时候刷新网页的时候，文章的封面是灰色的没有图片回显，而且访客和访问量因为数量相同，所以我个人认为可以删掉一个，能给大佬的主题提一点点小意见是我的荣幸。

**Comment by dhjddcn** [comment]
请提供图片或者视频

**Comment by wsy000-com** [comment]
![image](https://user-images.githubusercontent.com/67192668/222061407-57858eb5-6fff-44f6-8fb5-c32c4f584aca.png)

**Comment by dhjddcn** [comment]
你好非常感谢的建议  但是这里的访客和访问量是不相同的    一个点击量  一个访问量

**Comment by wsy000-com** [comment]
好的，期待大佬更加完善的主题，大佬的主题算是目前个人认为最好的，希望可以一直优化下去

**Comment by dhjddcn** [comment]
😄 谢谢支持 喜欢点个 ✨
