### ISSUE TITLE
更新`releases v2.0.2`后打开文章出错

### ISSUE THREAD

**Issue by AuroraStarry** [dhjddcn/halo-theme-butterfly#65]
### 是什么版本出现了此问题？

[releases v2.0.2](https://github.com/dhjddcn/halo-theme-butterfly/releases/tag/v2.0.2)

### Halo 版本

2.2.1

### 平台

桌面端

### 操作系统

ubuntu

### 浏览器

edge

### 在线站点地址

starrys.cn

### 描述缺陷

更新主题后打开文章出错
```text
500
Internal Server Error
Exception evaluating SpringEL expression: " !theme.config.post.enable_h_title ? ' enable_h_title' : ''" (template: "post" - line 97, col 14)
```

### 如何复现

打开任意文章

### 期望结果

正常查看文章

### 附加信息

<img width="395" alt="image" src="https://user-images.githubusercontent.com/79194954/222061236-7c52dbea-f5ef-4615-8b4b-e07da45045af.png">

**Comment by dhjddcn** [comment]
去文章模块保存一下看看

**Comment by AuroraStarry** [comment]
> 去文章模块保存一下看看

好的我去试试看

**Comment by AuroraStarry** [comment]
> 去文章模块保存一下看看

重新保存后打开还是500

**Comment by dhjddcn** [comment]
去主题的文章配置哪里选择一下文章标题那个 然后保存一下 
![image](https://user-images.githubusercontent.com/52057336/222062222-0dafb30e-3ecb-4cb2-aba6-ff299fd2c63a.png)

**Comment by AuroraStarry** [comment]
> 去主题的文章配置哪里选择一下文章标题那个 然后保存一下 ![image](https://user-images.githubusercontent.com/52057336/222062222-0dafb30e-3ecb-4cb2-aba6-ff299fd2c63a.png)

ok 好了感谢大佬
