### ISSUE TITLE
字体文件引用错误

### ISSUE THREAD

**Issue by PulSe-kun** [dhjddcn/halo-theme-butterfly#67]
### 是什么版本出现了此问题？

2.03

### Halo 版本

2.30

### 平台

桌面端

### 操作系统

win11

### 浏览器

谷歌

### 描述缺陷

这边字体文件命名少写了，应该XXX.min.css
![Snipaste_2023-03-01_22-59-09](https://user-images.githubusercontent.com/66857592/222179197-d1f12eed-a575-41ff-8dfc-3cc1bbd18c55.png)
还有个引用问题，我看了一下目录并没有
![Snipaste_2023-03-01_23-07-09](https://user-images.githubusercontent.com/66857592/222179657-2c2625dc-2c26-4a1e-8203-56af316403e0.png)

**Comment by dhjddcn** [comment]
字体文件已经添加
