### ISSUE TITLE
访问以下地址会出现500错误

### ISSUE THREAD

**Issue by maizi08** [dhjddcn/halo-theme-butterfly#69]
### 是什么版本出现了此问题？

2.03

### Halo 版本

2.3

### 平台

桌面端

### 操作系统

Win11

### 浏览器

edge

### 描述缺陷

访问https://example.com/root/.halo2/themes/theme-butterfly/templates/assets/font/false.min.css会出现500错误

### 如何复现

访问即可

### 期望结果

不再出现此错误

**Comment by maizi08** [comment]
![image](https://user-images.githubusercontent.com/112745722/222675910-859f17b4-791a-4596-b87d-b54b3fb1e575.png)

**Comment by dhjddcn** [comment]
![image](https://user-images.githubusercontent.com/52057336/222678164-57a7e9f7-b6f6-4abc-a755-ab1b3e225a36.png)
  你这是什么路径？？？

**Comment by dhjddcn** [comment]
站点发一下

**Comment by 9mlcy7** [comment]
借楼提个建议，把实际本机映射目录隐藏，避免暴露敏感信息

**Comment by dhjddcn** [comment]
> 借楼提个建议，把实际本机映射目录隐藏，避免暴露敏感信

没理解你的意思

**Comment by 9mlcy7** [comment]
![image](https://user-images.githubusercontent.com/51769096/223639086-200c63b1-5f97-47c6-92af-4eb2447fcea3.png)
这个地方的不要暴露本机目录

**Comment by dhjddcn** [comment]
> ![image](https://user-images.githubusercontent.com/51769096/223639086-200c63b1-5f97-47c6-92af-4eb2447fcea3.png) 这个地方的不要暴露本机目录

这个是报错信息 是halo 抛出来的
