### ISSUE TITLE
通关Halo2主题安装界面安装卡死在100%

### ISSUE THREAD

**Issue by ispace-top** [dhjddcn/halo-theme-butterfly#72]
### 是什么版本出现了此问题？

2.0.3

### Halo 版本

2.3.0

### 平台

桌面端

### 操作系统

MacOS 13.2.1 (22D68)

### 浏览器

chrome

### 在线站点地址

https://www.ispace.top

### 描述缺陷

通过界面上传主题卡在100%无进展，退出后上传失败

**Comment by dhjddcn** [comment]
> ### 是什么版本出现了此问题？
> 2.0.3
> 
> ### Halo 版本
> 2.3.0
> 
> ### 平台
> 桌面端
> 
> ### 操作系统
> MacOS 13.2.1 (22D68)
> 
> ### 浏览器
> chrome
> 
> ### 在线站点地址
> https://www.ispace.top
> 
> ### 描述缺陷
> 通过界面上传主题卡在100%无进展，退出后上传失败
> 
> ### 如何复现
> _No response_
> 
> ### 期望结果
> _No response_
> 
> ### 附加信息
> _No response_

我看你的站点 不是我开发的这个主题 该主题 开发者是：  https://github.com/liuzhihang/halo-theme-hao

**Comment by ispace-top** [comment]
😓尴尬死了。。。。哭错坟了。。。。

**Comment by dhjddcn** [comment]
咋安装不上去  截图看看

**Comment by ispace-top** [comment]
已经结案了。。。。。是Nginx配置的上传大小限制问题
