### ISSUE TITLE
开启深色模式搜索框内容文字颜色问题

### ISSUE THREAD

**Issue by 9mlcy7** [dhjddcn/halo-theme-butterfly#73]
### 是什么版本出现了此问题？

2.0.3

### Halo 版本

2.3.0

### 平台

桌面端

### 描述缺陷

![image](https://user-images.githubusercontent.com/51769096/223645605-1e4e5108-76bf-433d-990b-9ba38e58f34c.png)
![image](https://user-images.githubusercontent.com/51769096/223645661-ce9e01f1-d2d7-4485-af62-86a2e96508ec.png)

**Comment by 9mlcy7** [comment]
![47B6B2D9-7807-4955-86D7-A34AC4575FF6](https://user-images.githubusercontent.com/51769096/223725678-32cdc2b9-1c2f-4099-9960-b50bbd0a0250.png)
深色模式有些地方字体颜色需要亮一点

**Comment by 9mlcy7** [comment]
![D148F0FC-3F94-4B1E-92A6-C14D1C0277A5](https://user-images.githubusercontent.com/51769096/223725940-ad3d5151-5de8-4e2b-bbc8-d521b233e640.png)
移动端表情框定位问题

**Comment by dhjddcn** [comment]
搜索插件和评论插件都不包含在主题内

**Comment by dhjddcn** [comment]
评论插件  你切换以后需要刷新一下 真是评论插件的bug

**Comment by 9mlcy7** [comment]
是要把评论插件刷新一下还是什么

**Comment by dhjddcn** [comment]
刷新页面
