### ISSUE TITLE
请问公告在哪里配置

### ISSUE THREAD

**Issue by llwmeme** [dhjddcn/halo-theme-butterfly#74]
### 是什么版本出现了此问题？

2.0.3

### Halo 版本

2.3.0

### 平台

桌面端

### 描述缺陷

没找到公告配置的位置

**Comment by dhjddcn** [comment]
![image](https://user-images.githubusercontent.com/52057336/223934597-826cf21d-0306-47cb-9078-f9285fdf75aa.png)

**Comment by llwmeme** [comment]
好的多谢
