### ISSUE TITLE
希望文章頁面排版更加清晰

### ISSUE THREAD

**Issue by HimiCos** [dhjddcn/halo-theme-butterfly#75]
### 你当前使用的版本

2.3.0

### 你的建议是否涉及到一些现有的问题？

現在的排版總感覺內容比較混合在一起，如果不看目錄的話很容易搞不清楚一些內容的級別。比如說二級標題下有個三級標題，三級標題下有兩個四級標題。如果只有H2，H3，H4來區分，沒有制表符來區分，總感覺很亂。

### 描述你想实现的效果

雖然我也不清楚排版怎樣會好看一些，但是還是希望作者大大有考慮到這一點。
我也可以舉一些例子，比如上面的，可以把二級標題及內容顯示出來，三級四級隱藏，點擊即可展開。

**Comment by dhjddcn** [comment]
你的意思是默认展开目录吗

**Comment by HimiCos** [comment]
不是目錄，而是文章結構，比如二級標題和三級標題之間做區分，圖形上的區分，如果只是H2，H3這樣也不夠清晰

**Comment by dhjddcn** [comment]
？做了区分的吧

**Comment by dhjddcn** [comment]
截个图或者视频看下

**Comment by dhjddcn** [comment]
可以把二級標題及內容顯示出來，三級四級隱藏，點擊即可展開  这个在文章正文里面是没法这样做的

**Comment by HimiCos** [comment]
![CDBA9917-120F-48C4-8EBB-A315C6BBB908](https://user-images.githubusercontent.com/92566148/224912121-f045d8df-2c4c-44ff-85cd-7681d2aa888e.jpeg)
或者就是這樣，只是簡單一畫

**Comment by dhjddcn** [comment]
正文不能这样做 现在标题前面有h图标可以打开这个设置来区分是几级标题

**Comment by HimiCos** [comment]
好，但是我還有個疑問🤔️，就是我手動在標題前或者普通文本前加空格保存後不會生效

**Comment by dhjddcn** [comment]
你编辑一个文章  操作你的步骤  完了你把这给文章前台地址发我 我看下

**Comment by dhjddcn** [comment]
应该是halo这编辑器解析把空格去掉了

**Comment by HimiCos** [comment]
好👌 我去halo提交一下Issues
