### ISSUE TITLE
archives页面存在图片加载异常情况

### ISSUE THREAD

**Issue by YJ-B** [dhjddcn/halo-theme-butterfly#81]
### 是什么版本出现了此问题？

 2.0.3

### Halo 版本

 2.0.0

### 平台

桌面端

### 操作系统

MacOSX

### 浏览器

Chrome 110.0.5481.177 (Official Build) (arm64) 

### 在线站点地址

https://blog.viger.tech/archives/

### 描述缺陷

Archives站点下文章总览模块图片加载异常，使用的是随机图片接口，接口地址为：https://api.likepoems.com/img/mc

简单的从前端的Network标签下没有发现对api的请求

<img width="563" alt="image" src="https://user-images.githubusercontent.com/48652341/224634244-dd8b8607-a0df-4b56-8c15-1eb937fdd31d.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/48652341/224634673-a53994f7-ba6d-48a7-8c04-b2cf0f06b5db.png">

### 如何复现

配置好后直接访问/archives页面即可

### 期望结果

可以正常加载图片

**Comment by dhjddcn** [comment]
问题已经修复  我还改了一下

**Comment by YJ-B** [comment]
您好，您发给我的邮件已经收到，谢谢！This is an automatic reply, confirming that your e-mail was received.Thank you！
