### ISSUE TITLE
保存文章设置后出现“请求参数错误 schema violation”

### ISSUE THREAD

**Issue by kanezxk** [dhjddcn/halo-theme-butterfly#83]
### 是什么版本出现了此问题？

2.0.3

### Halo 版本

2.3.0

### 主题 版本

2.0.3

### 平台

桌面端

### 操作系统

win10

### 浏览器

firefox

### 描述缺陷

在后台文章设置中，点击保存后出现“请求参数错误 schema violation”。

http响应状态码为400，detail字段值如下：

Validation error(s) :
metadata.annotations: Type expected 'string', found 'boolean'. (code: 1027)
From: metadata.<#/components/schemas/Metadata>.annotations.<additionalProperties>.<type>
 of schema content.halo.run/v1alpha1/Post.

### 如何复现

在文章设置中，点击保存即可出现

### 期望结果

正常保存

**Comment by dhjddcn** [comment]
后台报错吗？

**Comment by kanezxk** [comment]
是的，在后台的文章管理中出现的

![图片](https://user-images.githubusercontent.com/64626673/224914930-b4ce316f-4724-403e-aef4-8beb2b29518e.png)

![图片](https://user-images.githubusercontent.com/64626673/224914980-e7655c61-1a4c-44a5-8c4a-d395cfbe3975.png)

**Comment by dhjddcn** [comment]
我是主题开发者 这问题你去halo官方反应一下  https://github.com/halo-dev/halo

**Comment by kanezxk** [comment]
好的，感谢你的解答，但我使用自带的earth主题就没有这个问题，不知道是什么原因
