### ISSUE TITLE
移动端回到顶部不起作用

### ISSUE THREAD

**Issue by unclecode1024** [dhjddcn/halo-theme-butterfly#85]
### 是什么版本出现了此问题？

只知道最新版本有这个问题，其他没有使用

### Halo 版本

2.3.1

### 主题 版本

2.0.3

### 平台

移动端

### 操作系统

HarmonyOS 3.0.0

### 浏览器

华为浏览器

### 在线站点地址

blog.ppxm.cn

### 描述缺陷

移动端回到顶部不起作用

**Comment by dhjddcn** [comment]
你的站点也不是我的主题呀
