### ISSUE TITLE
已经发布的文章，进行文章设置保存，提示服务器内部错误

### ISSUE THREAD

**Issue by azwwz** [dhjddcn/halo-theme-butterfly#88]
### 是什么版本出现了此问题？

2.0.4

### Halo 版本

2.3.2

### 主题 版本

2.0.4

### 平台

桌面端

### 操作系统

windows

### 浏览器

edge

### 描述缺陷

[点击查看错误图片](https://raw.githubusercontent.com/azwwz/halo-synology-picture1/master/%E8%BD%AF%E4%BB%B6%E6%B5%8B%E8%AF%95/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95/gengxincuowu.png)
如图所示
换回默认的地球主题后可以正常保存

### 如何复现

1.主题为butterfly
2.随便写一篇文章
3.点击相应文章后的设置选项
4.点击保存
5.静静等待20s左右

### 期望结果

提示：服务器内部错误

### 附加信息

[点击查看错误图片](https://raw.githubusercontent.com/azwwz/halo-synology-picture1/master/%E8%BD%AF%E4%BB%B6%E6%B5%8B%E8%AF%95/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95/gengxincuowu.png)

**Comment by azwwz** [comment]
写一篇文章后，先发布，然后再进行设置保存

**Comment by dhjddcn** [comment]
真是halo的问题  不是主题的问题

**Comment by azwwz** [comment]
欧克欧克
