### ISSUE TITLE
文章設置保存時顯示服務器內部錯誤 

### ISSUE THREAD

**Issue by HimiCos** [dhjddcn/halo-theme-butterfly#90]
### Halo 版本

2.3.2

### 主题 版本

2.0.4

### 浏览器

Edge

### 描述缺陷

詳細信息麻煩看一下: https://github.com/halo-dev/halo/issues/3533
辛苦了！

**Comment by azwwz** [comment]
刚回复我说这个是halo的问题，我上面提了一个相同的issue

**Comment by HimiCos** [comment]
我一開始也以為是Halo的問題，不過最後降級主題解決了。等待大佬修復吧。

**Comment by azwwz** [comment]
你现在用的是什么版本的halo和butterfly，想抄个作业

**Comment by HimiCos** [comment]
Halo：`2.3.2`
Butterfly：`2.3.2`

**Comment by azwwz** [comment]
ok感谢

**Comment by lipanpan-hub** [comment]
感谢

**Comment by lipanpan-hub** [comment]
我同样的问题

**Comment by lipanpan-hub** [comment]
我刚才测试了下: 
Halo：2.3.2
Butterfly：2.0.3
也是可以的

**Comment by HimiCos** [comment]
但是 Butterfly：`2.0.3` 會有更奇怪的bug，你可以設置刷新你的主頁就能發現。

**Comment by dhjddcn** [comment]
后台保存 不是主题的问题😅

**Comment by HimiCos** [comment]
確實不是主題的問題，但是刪除主題就好了欸😅

**Comment by lipanpan-hub** [comment]
```java
2023-03-19T11:07:28.872+08:00 ERROR 7 --- [or-http-epoll-1] a.w.r.e.AbstractErrorWebExceptionHandler : [0452d9e3-4332]  500 Server Error for HTTP GET "/themes/theme-butterfly/assets/css/null?date=1679195248537"

java.io.FileNotFoundException: /root/.halo2/themes/theme-butterfly/templates/assets/css/null
        at org.springframework.core.io.FileSystemResource.lastModified(FileSystemResource.java:354) ~[spring-core-6.0.6.jar:6.0.6]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/themes/theme-butterfly/assets/css/null?date=1679195248537" [ExceptionHandlingWebHandler]
```

**Comment by lipanpan-hub** [comment]
这个具体是啥原因呀  大佬指点一二

**Comment by lipanpan-hub** [comment]
> 但是 Butterfly：`2.0.3` 會有更奇怪的bug，你可以設置刷新你的主頁就能發現。

我暂时没有发现刷新主页之后 有啥问题 你遇到什么问题 可以告知我吗?

**Comment by HimiCos** [comment]
我也不想升級去給你展示bug了，目前已知 `2.0.3` 沒有bug。

**Comment by dhjddcn** [comment]
我的站点，我刚刚试了一下  没有问题😂😂

**Comment by lipanpan-hub** [comment]
> 

文章保存没有问题 但是在设置页面更新标题 发布就会有问题

**Comment by lipanpan-hub** [comment]
> 我的站点，我刚刚试了一下 没有问题😂😂

文章保存没有问题 但是在设置页面更新标题 发布就会有问题

**Comment by dhjddcn** [comment]
浮现了

**Comment by lipanpan-hub** [comment]
> 浮现了

嗯嗯 太好了

**Comment by ruibaby** [comment]
@dhjddcn 

https://github.com/dhjddcn/halo-theme-butterfly/blob/c4c3bda9a94ffbdb1ac7224303594bbce811fb00/annotation-setting.yaml#L32-L34

value 的值目前只能为 string 类型。文档：https://docs.halo.run/developer-guide/annotations-form#:~:text=%E5%9B%A0%E4%B8%BA%20metadata.annotations%20%E6%98%AF%E4%B8%80%E4%B8%AA%E9%94%AE%E5%80%BC%E9%83%BD%E4%B8%BA%E5%AD%97%E7%AC%A6%E4%B8%B2%E7%B1%BB%E5%9E%8B%E7%9A%84%E5%AF%B9%E8%B1%A1%EF%BC%8C%E6%89%80%E4%BB%A5%E8%A1%A8%E5%8D%95%E9%A1%B9%E7%9A%84%E5%80%BC%E5%BF%85%E9%A1%BB%E4%B8%BA%E5%AD%97%E7%AC%A6%E4%B8%B2%E7%B1%BB%E5%9E%8B%E3%80%82%E8%BF%99%E5%B0%B1%E6%84%8F%E5%91%B3%E7%9D%80%EF%BC%8CFormKit%20%E7%9A%84%20number%E3%80%81group%E3%80%81repeater%20%E7%AD%89%E7%B1%BB%E5%9E%8B%E7%9A%84%E8%BE%93%E5%85%A5%E7%BB%84%E4%BB%B6%E9%83%BD%E4%B8%8D%E8%83%BD%E4%BD%BF%E7%94%A8%E3%80%82

**Comment by HimiCos** [comment]
暫時解決了，謝謝大佬

**Comment by shisuiyi** [comment]
> 暫時解決了，謝謝大佬



> 暫時解決了，謝謝大佬

请问怎么解决的，我也遇到了

**Comment by dhjddcn** [comment]
> > 暫時解決了，謝謝大佬
> 
> > 暫時解決了，謝謝大佬
> 
> 请问怎么解决的，我也遇到了

升级主题

**Comment by HimiCos** [comment]
主題最新版本已經修復了這個問題

**Comment by shisuiyi** [comment]
> 主題最新版本已經修復了這個問題

好的
