### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by SlyLi** [dhjddcn/halo-theme-butterfly#91]
### 是什么版本出现了此问题？

最新版

### Halo 版本

2.3.0

### 主题 版本

2.04

### 平台

桌面端

### 操作系统

ubuntu

### 浏览器

chrome

### 描述缺陷

500
Internal Server Error
Exception evaluating SpringEL expression: "theme.config.other.enable_cdn_link ? theme.config.other.cdn_link : #theme.assets('/')" (template: "modules/layout" - line 4, col 7)

### 如何复现

启动主题就这样了，我猜测因为 docker运行halo时设置   halo.external-url=/ 出现的问题

**Comment by dhjddcn** [comment]
去其他配置里面保存一下看看

**Comment by SlyLi** [comment]
> 去其他配置里面保存一下看看

好了 谢谢
