### ISSUE TITLE
文章访问量一直是0

### ISSUE THREAD

**Issue by chengbaobao630** [dhjddcn/halo-theme-butterfly#92]
### 是什么版本出现了此问题？

2.0.3

### Halo 版本

2.3.0

### 主题 版本

2.0.3

### 平台

桌面端

### 操作系统

macos

### 浏览器

chrome

### 在线站点地址

blog.bichuck.com

### 描述缺陷

每一篇文章的访问量都是0，站点访问量有数据且>50

### 如何复现

<img width="146" alt="image" src="https://user-images.githubusercontent.com/15663580/226489574-9c652ef8-f305-41d5-864d-e8c0be44c90d.png">
<img width="184" alt="image" src="https://user-images.githubusercontent.com/15663580/226489968-95a9ffaa-af33-4a67-ac2d-27483a5f1c44.png">

### 期望结果

访问次数增加

**Comment by dhjddcn** [comment]
看了你的站点也不是我主题啊
