### ISSUE TITLE
不能发布文章

### ISSUE THREAD

**Issue by chengbaobao630** [dhjddcn/halo-theme-butterfly#93]
### 是什么版本出现了此问题？

2.0.4

### Halo 版本

2.3.0

### 主题 版本

2.0.4

### 平台

桌面端

### 操作系统

 docker-ubuntu

### 浏览器

chrome

### 在线站点地址

blog.bichuck.com

### 描述缺陷

保存修改和发布文章的时候报错：schema异常

### 如何复现

每一次提交文章都会

### 期望结果

正常提交

**Comment by oops-fanglin** [comment]
我也遇到一样的问题，找了一圈应该是这个原因https://github.com/halo-dev/halo/issues/3533#issuecomment-1474872864

**Comment by dhjddcn** [comment]
请升级主题为最新版
