### ISSUE TITLE
关于页面报500错误

### ISSUE THREAD

**Issue by shisuiyi** [dhjddcn/halo-theme-butterfly#98]
### 是什么版本出现了此问题？

最新版

### Halo 版本

2.3.2

### 主题 版本

 2.0.4

### 平台

桌面端

### 在线站点地址

https://www.shibuyu.fun/

### 描述缺陷

进入关于页面报错
`Exception evaluating SpringEL expression: " !theme.config.single.enable_h_title ? ' enable_h_title' : ''" (template: "page" - line 54, col 14)`

**Comment by dhjddcn** [comment]
去独立于页保存一下  把主题升级为最新版本吧

**Comment by shisuiyi** [comment]
主题已经是最新的了

**Comment by shisuiyi** [comment]
> 去独立于页保存一下 把主题升级为最新版本吧
主题已经是最新的了

**Comment by shisuiyi** [comment]
> 去独立于页保存一下 把主题升级为最新版本吧

明白了，谢谢了。可以了保存一下就行

**Comment by shisuiyi** [comment]
独立页保存一下即可
