### ISSUE TITLE
应用了当前主题，文章会无法保存修改！

### ISSUE THREAD

**Issue by trdeep** [dhjddcn/halo-theme-butterfly#99]
### 是什么版本出现了此问题？

应用了当前主题，文章会无法保存修改。切换回默认主题就可以

### Halo 版本

2.3.2

### 主题 版本

2.0.4

### 平台

桌面端

### 操作系统

linux

### 在线站点地址

https://blog.treedeep.cn/

### 描述缺陷

 应用了当前主题，文章会无法保存修改。切换回默认主题就可以

用 docker-compose 部署的

<img width="780" alt="image" src="https://user-images.githubusercontent.com/119095555/227699458-bf2c1af1-781c-44d4-8f16-eef9d0411efa.png">

**Comment by HimiCos** [comment]
#90
